use std::ffi::c_void;
use std::marker::PhantomData;

/// Trait implemented by ABI descriptors generated by [`crate::xabi`].
///
/// Exporting modules do not implement this manually in normal use; the generated
/// ABI type is consumed by [`crate::module`].
pub trait XabiContract<P: 'static> {
    /// Stable ABI identifier exported by this contract.
    const ID: &'static str;

    /// Export a concrete implementation as an ABI-specific vtable.
    fn export(plugin: P) -> *mut c_void;
}

/// Sendable wrapper for raw pointers that are only dereferenced on a known-safe thread.
///
/// This is useful when a raw ABI pointer must be moved into an async task but
/// the caller controls where it is dereferenced.
///
/// ```
/// let mut value = 1_u32;
/// let ptr = xabi::SendPtr::new(&mut value as *mut u32);
/// let raw = ptr.as_ptr();
/// unsafe { *raw = 2 };
/// assert_eq!(value, 2);
/// ```
pub struct SendPtr<T> {
    value: usize,
    _marker: PhantomData<*mut T>,
}

impl<T> SendPtr<T> {
    /// Wrap a raw mutable pointer.
    pub fn new(ptr: *mut T) -> Self {
        Self {
            value: ptr as usize,
            _marker: PhantomData,
        }
    }

    /// Return the wrapped raw pointer.
    pub fn as_ptr(self) -> *mut T {
        self.value as *mut T
    }
}

unsafe impl<T> Send for SendPtr<T> {}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_send<T: Send>() {}

    #[test]
    fn send_ptr_is_send() {
        assert_send::<SendPtr<u8>>();
    }

    #[test]
    fn send_ptr_roundtrips_pointer_value() {
        let mut value = 5_u32;
        let ptr = &mut value as *mut u32;

        assert_eq!(SendPtr::new(ptr).as_ptr(), ptr);
    }
}
